In [1]:
# Step 1: Import Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score

In [2]:
# Step 2: Social network ads
ads = pd.read_csv('/content/drive/MyDrive/Datasets/Social_Network_Ads.csv')
ads.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [3]:
# Step 3: Initialize the data frame
data = pd.DataFrame(ads)
data.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [4]:
# Step 4: Split dependent variable and independent variables
X = data.drop(['Purchased'], axis=1)
y = data['Purchased']

In [5]:
# Step 5: Train–Test Split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [6]:
# Step 6: Train Logistic Regression model
from sklearn.linear_model import LogisticRegression

# Apply one-hot encoding to the 'Gender' column
X_train_encoded = pd.get_dummies(X_train, columns=['Gender'], drop_first=True)
X_test_encoded = pd.get_dummies(X_test, columns=['Gender'], drop_first=True)

model = LogisticRegression()
model.fit(X_train_encoded, y_train)

# Step 7: Predict test data
y_pred = model.predict(X_test_encoded)

In [7]:
# Step 8: Build Confusion Matrix
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print(cm)

[[50  2]
 [ 7 21]]

In [8]:
# Step 9: Compute evaluation metrics

from sklearn.metrics import accuracy_score, precision_score, recall_score

accuracy = accuracy_score(y_test, y_pred)
error_rate = 1 - accuracy
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)

print("Accuracy:", accuracy)
print("Error Rate:", error_rate)
print("Precision:", precision)
print("Recall:", recall)

Accuracy: 0.8875
Error Rate: 0.11250000000000004
Precision: 0.9130434782608695
Recall: 0.75